import torch
from rlpyt.models.mlp import MlpModel as MlpModel
from rlpyt.models.running_mean_std import RunningMeanStdModel as RunningMeanStdModel
from rlpyt.utils.collections import namedarraytuple as namedarraytuple
from rlpyt.utils.tensor import infer_leading_dims as infer_leading_dims, restore_leading_dims as restore_leading_dims
from typing import Any, Optional

ValueInfo: Any
RnnState: Any

class CppoModel(torch.nn.Module):
    body: Any = ...
    lstm: Any = ...
    mu: Any = ...
    value: Any = ...
    constraint: Any = ...
    log_std: Any = ...
    obs_rms: Any = ...
    var_clip: Any = ...
    normalize_observation: Any = ...
    def __init__(self, observation_shape: Any, action_size: Any, hidden_sizes: Optional[Any] = ..., lstm_size: Optional[Any] = ..., lstm_skip: bool = ..., constraint: bool = ..., hidden_nonlinearity: str = ..., mu_nonlinearity: str = ..., init_log_std: float = ..., normalize_observation: bool = ..., var_clip: float = ...) -> None: ...
    def forward(self, observation: Any, prev_action: Any, prev_reward: Any, init_rnn_state: Optional[Any] = ...): ...
    def update_obs_rms(self, observation: Any) -> None: ...
