# Stubs for rlpyt.agents.dqn.r2d1_agent (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from rlpyt.agents.base import AlternatingRecurrentAgentMixin, RecurrentAgentMixin
from rlpyt.agents.dqn.dqn_agent import DqnAgent
from typing import Any

AgentInfo: Any

class R2d1AgentBase(DqnAgent):
    def __call__(self, observation: Any, prev_action: Any, prev_reward: Any, init_rnn_state: Any): ...
    def step(self, observation: Any, prev_action: Any, prev_reward: Any): ...
    def target(self, observation: Any, prev_action: Any, prev_reward: Any, init_rnn_state: Any): ...

class R2d1Agent(RecurrentAgentMixin, R2d1AgentBase): ...
class R2d1AlternatingAgent(AlternatingRecurrentAgentMixin, R2d1AgentBase): ...
