from rlpyt.agents.base import AgentStep as AgentStep, AlternatingRecurrentAgentMixin as AlternatingRecurrentAgentMixin, RecurrentAgentMixin as RecurrentAgentMixin
from rlpyt.agents.dqn.dqn_agent import DqnAgent as DqnAgent
from rlpyt.utils.buffer import buffer_func as buffer_func, buffer_method as buffer_method, buffer_to as buffer_to
from rlpyt.utils.collections import namedarraytuple as namedarraytuple
from typing import Any

AgentInfo: Any

class R2d1AgentBase(DqnAgent):
    def __call__(self, observation: Any, prev_action: Any, prev_reward: Any, init_rnn_state: Any): ...
    def step(self, observation: Any, prev_action: Any, prev_reward: Any): ...
    def target(self, observation: Any, prev_action: Any, prev_reward: Any, init_rnn_state: Any): ...

class R2d1Agent(RecurrentAgentMixin, R2d1AgentBase): ...
class R2d1AlternatingAgent(AlternatingRecurrentAgentMixin, R2d1AgentBase): ...
