from collections import namedtuple
from rlpyt.algos.utils import valid_from_done as valid_from_done
from rlpyt.ul.algos.ul_for_rl.base import BaseUlAlgorithm as BaseUlAlgorithm
from rlpyt.ul.models.ul.encoders import EncoderModel as EncoderModel
from rlpyt.ul.replays.ul_for_rl_replay import UlForRlReplayBuffer as UlForRlReplayBuffer
from rlpyt.utils.buffer import buffer_to as buffer_to
from rlpyt.utils.logging import logger as logger
from rlpyt.utils.quick_args import save__init__args as save__init__args
from rlpyt.utils.tensor import to_onehot as to_onehot, valid_mean as valid_mean
from typing import Any, Optional

IGNORE_INDEX: int

OptInfo = namedtuple('OptInfo', ['cpcLoss', 'cpcAccuracy1', 'cpcAccuracy2', 'cpcAccuracyTm1', 'cpcAccuracyTm2', 'activationLoss', 'gradNorm', 'convActivation'])

ValInfo = namedtuple('ValInfo', ['cpcLoss', 'cpcAccuracy1', 'cpcAccuracy2', 'cpcAccuracyTm1', 'cpcAccuracyTm2', 'convActivation'])

class CPC(BaseUlAlgorithm):
    opt_info_fields: Any = ...
    c_e_loss: Any = ...
    batch_size: Any = ...
    def __init__(self, batch_B: Any, batch_T: Any, learning_rate: Any, replay_filepath: Any, warmup_T: int = ..., rnn_size: int = ..., latent_size: int = ..., OptimCls: Any = ..., optim_kwargs: Optional[Any] = ..., initial_state_dict: Optional[Any] = ..., clip_grad_norm: float = ..., validation_split: float = ..., n_validation_batches: int = ..., EncoderCls: Any = ..., encoder_kwargs: Optional[Any] = ..., ReplayCls: Any = ..., onehot_actions: bool = ..., activation_loss_coefficient: float = ..., learning_rate_anneal: Optional[Any] = ..., learning_rate_warmup: int = ...) -> None: ...
    device: Any = ...
    encoder: Any = ...
    prediction_rnn: Any = ...
    transforms: Any = ...
    def initialize(self, n_updates: Any, cuda_idx: Optional[Any] = ...) -> None: ...
    def optimize(self, itr: Any): ...
    def cpc_loss(self, samples: Any): ...
    def validation(self, itr: Any): ...
    def state_dict(self): ...
    def load_state_dict(self, state_dict: Any) -> None: ...
    def parameters(self) -> None: ...
    def named_parameters(self) -> None: ...
    def eval(self) -> None: ...
    def train(self) -> None: ...
