from collections import namedtuple
from rlpyt.algos.utils import valid_from_done as valid_from_done
from rlpyt.distributions.categorical import Categorical as Categorical, DistInfo as DistInfo
from rlpyt.ul.algos.ul_for_rl.base import BaseUlAlgorithm as BaseUlAlgorithm
from rlpyt.ul.algos.utils.data_augs import random_shift as random_shift
from rlpyt.ul.models.inv_models import InverseModel as InverseModel
from rlpyt.ul.models.ul.encoders import EncoderModel as EncoderModel
from rlpyt.ul.replays.ul_for_rl_replay import UlForRlReplayBuffer as UlForRlReplayBuffer
from rlpyt.utils.buffer import buffer_to as buffer_to
from rlpyt.utils.logging import logger as logger
from rlpyt.utils.quick_args import save__init__args as save__init__args
from typing import Any, Optional

IGNORE_INDEX: int

OptInfo = namedtuple('OptInfo', ['invLoss', 'entLoss', 'accuracy', 'perplexity', 'activationLoss', 'gradNorm', 'convActivation'])

ValInfo = namedtuple('ValInfo', ['invLoss', 'entLoss', 'accuracy', 'perplexity', 'convActivation'])

class Inverse(BaseUlAlgorithm):
    opt_info_fields: Any = ...
    c_e_loss: Any = ...
    def __init__(self, batch_size: Any, learning_rate: Any, replay_filepath: Any, delta_T: int = ..., OptimCls: Any = ..., optim_kwargs: Optional[Any] = ..., initial_state_dict: Optional[Any] = ..., clip_grad_norm: float = ..., EncoderCls: Any = ..., encoder_kwargs: Optional[Any] = ..., ReplayCls: Any = ..., onehot_actions: bool = ..., activation_loss_coefficient: float = ..., learning_rate_anneal: Optional[Any] = ..., learning_rate_warmup: int = ..., random_shift_prob: float = ..., random_shift_pad: int = ..., InverseModelCls: Any = ..., inverse_model_kwargs: Optional[Any] = ..., entropy_loss_coeff: float = ..., validation_split: float = ..., n_validation_batches: int = ...) -> None: ...
    device: Any = ...
    encoder: Any = ...
    distribution: Any = ...
    inverse_model: Any = ...
    def initialize(self, n_updates: Any, cuda_idx: Optional[Any] = ...) -> None: ...
    def optimize(self, itr: Any): ...
    def inverse_loss(self, samples: Any): ...
    def validation(self, itr: Any): ...
    def state_dict(self): ...
    def load_state_dict(self, state_dict: Any) -> None: ...
    def parameters(self) -> None: ...
    def named_parameters(self) -> None: ...
    def eval(self) -> None: ...
    def train(self) -> None: ...
