from collections import namedtuple
from rlpyt.algos.utils import valid_from_done as valid_from_done
from rlpyt.models.utils import update_state_dict as update_state_dict
from rlpyt.ul.algos.ul_for_rl.base import BaseUlAlgorithm as BaseUlAlgorithm
from rlpyt.ul.models.ul.atc_models import ContrastModel as ContrastModel
from rlpyt.ul.models.ul.stdim_models import StDimEncoderModel as StDimEncoderModel, StDimGlobalLocalContrastModel as StDimGlobalLocalContrastModel, StDimLocalLocalContrastModel as StDimLocalLocalContrastModel
from rlpyt.ul.replays.ul_for_rl_replay import UlForRlReplayBuffer as UlForRlReplayBuffer
from rlpyt.utils.buffer import buffer_to as buffer_to
from rlpyt.utils.logging import logger as logger
from rlpyt.utils.quick_args import save__init__args as save__init__args
from typing import Any, Optional

IGNORE_INDEX: int

OptInfo = namedtuple('OptInfo', ['stdimLoss', 'ggLoss', 'glLoss', 'llLoss', 'ggAccuracy', 'glAccuracy', 'llAccuracy', 'activationLoss', 'gradNorm', 'convActivation'])

ValInfo = namedtuple('ValInfo', ['stdimLoss', 'ggLoss', 'glLoss', 'llLoss', 'ggAccuracy', 'glAccuracy', 'llAccuracy', 'convActivation'])

class STDIM(BaseUlAlgorithm):
    opt_info_fields: Any = ...
    c_e_loss: Any = ...
    batch_size: Any = ...
    def __init__(self, replay_filepath: Any, learning_rate: Any, batch_B: int = ..., batch_T: int = ..., delta_T: int = ..., use_global_global: bool = ..., use_global_local: bool = ..., use_local_local: bool = ..., local_conv_layer: int = ..., latent_size: int = ..., target_update_tau: float = ..., target_update_interval: int = ..., OptimCls: Any = ..., optim_kwargs: Optional[Any] = ..., initial_state_dict: Optional[Any] = ..., clip_grad_norm: float = ..., EncoderCls: Any = ..., encoder_kwargs: Optional[Any] = ..., ReplayCls: Any = ..., anchor_hidden_sizes: int = ..., activation_loss_coefficient: float = ..., learning_rate_anneal: Optional[Any] = ..., learning_rate_warmup: int = ..., validation_split: float = ..., n_validation_batches: int = ...) -> None: ...
    device: Any = ...
    encoder: Any = ...
    target_encoder: Any = ...
    gg_contrast: Any = ...
    gl_contrast: Any = ...
    ll_contrast: Any = ...
    def initialize(self, n_updates: Any, cuda_idx: Optional[Any] = ...) -> None: ...
    def optimize(self, itr: Any): ...
    def stdim_loss(self, samples: Any): ...
    def validation(self, itr: Any): ...
    def state_dict(self): ...
    def load_state_dict(self, state_dict: Any) -> None: ...
    def parameters(self) -> None: ...
    def named_parameters(self) -> None: ...
    def eval(self) -> None: ...
    def train(self) -> None: ...
