from collections import namedtuple
from rlpyt.algos.utils import valid_from_done as valid_from_done
from rlpyt.distributions.categorical import Categorical as Categorical
from rlpyt.ul.algos.ul_for_rl.base import BaseUlAlgorithm as BaseUlAlgorithm
from rlpyt.ul.models.ul.encoders import EncoderModel as EncoderModel
from rlpyt.ul.models.ul.vae_models import VaeDecoderModel as VaeDecoderModel, VaeHeadModel as VaeHeadModel
from rlpyt.ul.replays.ul_for_rl_replay import UlForRlReplayBuffer as UlForRlReplayBuffer
from rlpyt.utils.buffer import buffer_to as buffer_to
from rlpyt.utils.logging import logger as logger
from rlpyt.utils.quick_args import save__init__args as save__init__args
from rlpyt.utils.tensor import valid_mean as valid_mean
from typing import Any, Optional

IGNORE_INDEX: int

OptInfo = namedtuple('OptInfo', ['reconLoss', 'klLoss', 'activationLoss', 'gradNorm', 'convActivation'])

ValInfo = namedtuple('ValInfo', ['reconLoss', 'klLoss', 'convActivation'])

class VAE(BaseUlAlgorithm):
    opt_info_fields: Any = ...
    c_e_loss: Any = ...
    def __init__(self, batch_size: Any, learning_rate: Any, replay_filepath: Any, delta_T: int = ..., OptimCls: Any = ..., optim_kwargs: Optional[Any] = ..., initial_state_dict: Optional[Any] = ..., clip_grad_norm: float = ..., EncoderCls: Any = ..., encoder_kwargs: Optional[Any] = ..., latent_size: int = ..., ReplayCls: Any = ..., activation_loss_coefficient: float = ..., learning_rate_anneal: Optional[Any] = ..., learning_rate_warmup: int = ..., VaeHeadCls: Any = ..., hidden_sizes: Optional[Any] = ..., DecoderCls: Any = ..., decoder_kwargs: Optional[Any] = ..., kl_coeff: float = ..., onehot_action: bool = ..., validation_split: float = ..., n_validation_batches: int = ...) -> None: ...
    device: Any = ...
    encoder: Any = ...
    distribution: Any = ...
    vae_head: Any = ...
    decoder: Any = ...
    def initialize(self, n_updates: Any, cuda_idx: Optional[Any] = ...) -> None: ...
    def optimize(self, itr: Any): ...
    def vae_loss(self, samples: Any): ...
    def validation(self, itr: Any): ...
    def state_dict(self): ...
    def load_state_dict(self, state_dict: Any) -> None: ...
    def parameters(self) -> None: ...
    def named_parameters(self) -> None: ...
    def eval(self) -> None: ...
    def train(self) -> None: ...
