# Stubs for rlpyt.replays.non_sequence.frame (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from rlpyt.replays.async_ import AsyncReplayBufferMixin
from rlpyt.replays.frame import FrameBufferMixin
from rlpyt.replays.non_sequence.n_step import NStepReturnBuffer
from rlpyt.replays.non_sequence.prioritized import PrioritizedReplay
from rlpyt.replays.non_sequence.uniform import UniformReplay
from typing import Any

class NStepFrameBuffer(FrameBufferMixin, NStepReturnBuffer):
    def extract_observation(self, T_idxs: Any, B_idxs: Any): ...

class UniformReplayFrameBuffer(UniformReplay, NStepFrameBuffer): ...
class PrioritizedReplayFrameBuffer(PrioritizedReplay, NStepFrameBuffer): ...
class AsyncUniformReplayFrameBuffer(AsyncReplayBufferMixin, UniformReplayFrameBuffer): ...
class AsyncPrioritizedReplayFrameBuffer(AsyncReplayBufferMixin, PrioritizedReplayFrameBuffer): ...
