# Stubs for rlpyt.replays.non_sequence.n_step (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from rlpyt.replays.n_step import BaseNStepReturnBuffer
from typing import Any

SamplesFromReplay: Any

class NStepReturnBuffer(BaseNStepReturnBuffer):
    def extract_batch(self, T_idxs: Any, B_idxs: Any): ...
    def extract_observation(self, T_idxs: Any, B_idxs: Any): ...
