from rlpyt.replays.async_ import AsyncReplayBufferMixin as AsyncReplayBufferMixin
from rlpyt.replays.non_sequence.n_step import NStepReturnBuffer as NStepReturnBuffer
from typing import Any

class UniformReplay:
    def sample_batch(self, batch_B: Any): ...
    def sample_idxs(self, batch_B: Any): ...

class UniformReplayBuffer(UniformReplay, NStepReturnBuffer): ...
class AsyncUniformReplayBuffer(AsyncReplayBufferMixin, UniformReplayBuffer): ...
