# Stubs for rlpyt.replays.non_sequence.uniform (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from rlpyt.replays.async_ import AsyncReplayBufferMixin
from rlpyt.replays.non_sequence.n_step import NStepReturnBuffer
from typing import Any

class UniformReplay:
    def sample_batch(self, batch_B: Any): ...
    def sample_idxs(self, batch_B: Any): ...

class UniformReplayBuffer(UniformReplay, NStepReturnBuffer): ...
class AsyncUniformReplayBuffer(AsyncReplayBufferMixin, UniformReplayBuffer): ...
