# Stubs for rlpyt.agents.dqn.atari.atari_dqn_agent (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from rlpyt.agents.dqn.atari.mixin import AtariMixin
from rlpyt.agents.dqn.dqn_agent import DqnAgent
from typing import Any

class AtariDqnAgent(AtariMixin, DqnAgent):
    def __init__(self, ModelCls: Any = ..., **kwargs: Any) -> None: ...
