# Stubs for rlpyt.agents.dqn.atari.atari_catdqn_agent (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from rlpyt.agents.dqn.atari.mixin import AtariMixin
from rlpyt.agents.dqn.catdqn_agent import CatDqnAgent
from typing import Any

class AtariCatDqnAgent(AtariMixin, CatDqnAgent):
    def __init__(self, ModelCls: Any = ..., **kwargs: Any) -> None: ...
