# Stubs for rlpyt.agents.dqn.atari.mixin (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class AtariMixin:
    def make_env_to_model_kwargs(self, env_spaces: Any): ...
