# Stubs for rlpyt.envs.base (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from collections import namedtuple
from typing import Any

EnvStep = namedtuple('EnvStep', ['observation', 'reward', 'done', 'env_info'])

EnvInfo = namedtuple('EnvInfo', [])

EnvSpaces = namedtuple('EnvSpaces', ['observation', 'action'])

class Env:
    def step(self, action: Any) -> None: ...
    def reset(self) -> None: ...
    @property
    def action_space(self): ...
    @property
    def observation_space(self): ...
    @property
    def spaces(self): ...
    @property
    def horizon(self) -> None: ...
    def close(self) -> None: ...
