from rlpyt.runners.minibatch_rl import MinibatchRlEval as MinibatchRlEval
from rlpyt.utils.logging import logger as logger
from rlpyt.utils.prog_bar import ProgBarCounter as ProgBarCounter
from typing import Any

class MinibatchRlEvalEnvStep(MinibatchRlEval):
    def __init__(self, *args: Any, frame_skip: int = ..., **kwargs: Any) -> None: ...
    pbar: Any = ...
    def log_diagnostics(self, itr: Any, eval_traj_infos: Any, eval_time: Any) -> None: ...
