from rlpyt.runners.minibatch_rl import MinibatchRl as MinibatchRl, MinibatchRlEval as MinibatchRlEval
from rlpyt.ul.runners.envstep_runner import MinibatchRlEvalEnvStep as MinibatchRlEvalEnvStep
from rlpyt.utils.logging import logger as logger
from rlpyt.utils.prog_bar import ProgBarCounter as ProgBarCounter
from typing import Any

class ReplaySaverMixin:
    def log_diagnostics(self, itr: Any, *args: Any, **kwargs: Any) -> None: ...

class MinibatchRlReplaySaver(ReplaySaverMixin, MinibatchRl): ...
class MinibatchRlEvalReplaySaver(ReplaySaverMixin, MinibatchRlEval): ...
class MinibatchRlEvalEnvStepReplaySaver(ReplaySaverMixin, MinibatchRlEvalEnvStep): ...
