# Stubs for rlpyt.agents.pg.atari (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from rlpyt.agents.pg.categorical import AlternatingRecurrentCategoricalPgAgent, CategoricalPgAgent, RecurrentCategoricalPgAgent
from typing import Any

class AtariMixin:
    def make_env_to_model_kwargs(self, env_spaces: Any): ...

class AtariFfAgent(AtariMixin, CategoricalPgAgent):
    def __init__(self, ModelCls: Any = ..., **kwargs: Any) -> None: ...

class AtariLstmAgent(AtariMixin, RecurrentCategoricalPgAgent):
    def __init__(self, ModelCls: Any = ..., **kwargs: Any) -> None: ...

class AlternatingAtariLstmAgent(AtariMixin, AlternatingRecurrentCategoricalPgAgent):
    def __init__(self, ModelCls: Any = ..., **kwargs: Any) -> None: ...
