from rlpyt.agents.pg.gaussian import AlternatingRecurrentGaussianPgAgent as AlternatingRecurrentGaussianPgAgent, GaussianPgAgent as GaussianPgAgent, RecurrentGaussianPgAgent as RecurrentGaussianPgAgent
from rlpyt.models.pg.mujoco_ff_model import MujocoFfModel as MujocoFfModel
from rlpyt.models.pg.mujoco_lstm_model import MujocoLstmModel as MujocoLstmModel
from rlpyt.utils.buffer import buffer_to as buffer_to
from typing import Any

class MujocoMixin:
    def make_env_to_model_kwargs(self, env_spaces: Any): ...
    def update_obs_rms(self, observation: Any) -> None: ...
    def data_parallel(self, *args: Any, **kwargs: Any) -> None: ...

class MujocoFfAgent(MujocoMixin, GaussianPgAgent):
    def __init__(self, ModelCls: Any = ..., **kwargs: Any) -> None: ...

class MujocoLstmAgent(MujocoMixin, RecurrentGaussianPgAgent):
    def __init__(self, ModelCls: Any = ..., **kwargs: Any) -> None: ...

class AlternatingMujocoLstmAgent(MujocoMixin, AlternatingRecurrentGaussianPgAgent):
    def __init__(self, ModelCls: Any = ..., **kwargs: Any) -> None: ...
