# Stubs for rlpyt.agents.pg.mujoco (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from rlpyt.agents.pg.gaussian import AlternatingRecurrentGaussianPgAgent, GaussianPgAgent, RecurrentGaussianPgAgent
from typing import Any

class MujocoMixin:
    def make_env_to_model_kwargs(self, env_spaces: Any): ...
    def update_obs_rms(self, observation: Any) -> None: ...
    def data_parallel(self, *args: Any, **kwargs: Any) -> None: ...

class MujocoFfAgent(MujocoMixin, GaussianPgAgent):
    def __init__(self, ModelCls: Any = ..., **kwargs: Any) -> None: ...

class MujocoLstmAgent(MujocoMixin, RecurrentGaussianPgAgent):
    def __init__(self, ModelCls: Any = ..., **kwargs: Any) -> None: ...

class AlternatingMujocoLstmAgent(MujocoMixin, AlternatingRecurrentGaussianPgAgent):
    def __init__(self, ModelCls: Any = ..., **kwargs: Any) -> None: ...
