import torch
from rlpyt.models.mlp import MlpModel as MlpModel
from rlpyt.utils.tensor import infer_leading_dims as infer_leading_dims
from typing import Any

class ContrastModel(torch.nn.Module):
    anchor_mlp: Any = ...
    W: Any = ...
    def __init__(self, latent_size: Any, anchor_hidden_sizes: Any) -> None: ...
    def forward(self, anchor: Any, positive: Any): ...
