# Stubs for rlpyt.samplers.buffer (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def build_samples_buffer(agent: Any, env: Any, batch_spec: Any, bootstrap_value: bool = ..., agent_shared: bool = ..., env_shared: bool = ..., subprocess: bool = ..., examples: Optional[Any] = ...): ...
def get_example_outputs(agent: Any, env: Any, examples: Any, subprocess: bool = ...) -> None: ...
