from rlpyt.utils.collections import AttrDict as AttrDict, namedarraytuple as namedarraytuple
from typing import Any

Samples: Any
AgentSamples: Any
AgentSamplesBsv: Any
EnvSamples: Any

class BatchSpec:
    @property
    def size(self): ...

class TrajInfo(AttrDict):
    Length: int = ...
    Return: int = ...
    NonzeroRewards: int = ...
    DiscountedReturn: int = ...
    def __init__(self, **kwargs: Any) -> None: ...
    def step(self, observation: Any, action: Any, reward: Any, done: Any, agent_info: Any, env_info: Any) -> None: ...
    def terminate(self, observation: Any): ...
