# Stubs for rlpyt.samplers.serial.collectors (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from rlpyt.samplers.collectors import BaseEvalCollector
from typing import Any, Optional

class SerialEvalCollector(BaseEvalCollector):
    def __init__(self, envs: Any, agent: Any, TrajInfoCls: Any, max_T: Any, max_trajectories: Optional[Any] = ...) -> None: ...
    def collect_evaluation(self, itr: Any): ...
