from rlpyt.utils.tensor import valid_mean as valid_mean
from typing import Any, Optional

DistInfo: Any

class Distribution:
    @property
    def dim(self) -> None: ...
    def sample(self, dist_info: Any) -> None: ...
    def kl(self, old_dist_info: Any, new_dist_info: Any) -> None: ...
    def mean_kl(self, old_dist_info: Any, new_dist_info: Any, valid: Any) -> None: ...
    def log_likelihood(self, x: Any, dist_info: Any) -> None: ...
    def likelihood_ratio(self, x: Any, old_dist_info: Any, new_dist_info: Any) -> None: ...
    def entropy(self, dist_info: Any) -> None: ...
    def perplexity(self, dist_info: Any): ...
    def mean_entropy(self, dist_info: Any, valid: Optional[Any] = ...): ...
    def mean_perplexity(self, dist_info: Any, valid: Optional[Any] = ...): ...
