from rlpyt.distributions.base import Distribution as Distribution
from rlpyt.distributions.discrete import DiscreteMixin as DiscreteMixin
from rlpyt.utils.collections import namedarraytuple as namedarraytuple
from rlpyt.utils.tensor import select_at_indexes as select_at_indexes, valid_mean as valid_mean
from typing import Any, Optional

EPS: float
DistInfo: Any

class Categorical(DiscreteMixin, Distribution):
    def kl(self, old_dist_info: Any, new_dist_info: Any): ...
    def mean_kl(self, old_dist_info: Any, new_dist_info: Any, valid: Optional[Any] = ...): ...
    def sample(self, dist_info: Any): ...
    def entropy(self, dist_info: Any): ...
    def log_likelihood(self, indexes: Any, dist_info: Any): ...
    def likelihood_ratio(self, indexes: Any, old_dist_info: Any, new_dist_info: Any): ...
