from rlpyt.utils.tensor import from_onehot as from_onehot, to_onehot as to_onehot
from typing import Any, Optional

class DiscreteMixin:
    dtype: Any = ...
    onehot_dtype: Any = ...
    def __init__(self, dim: Any, dtype: Any = ..., onehot_dtype: Any = ...) -> None: ...
    @property
    def dim(self): ...
    def to_onehot(self, indexes: Any, dtype: Optional[Any] = ...): ...
    def from_onehot(self, onehot: Any, dtype: Optional[Any] = ...): ...
