from rlpyt.distributions.base import Distribution as Distribution
from rlpyt.distributions.discrete import DiscreteMixin as DiscreteMixin
from typing import Any, Optional

class EpsilonGreedy(DiscreteMixin, Distribution):
    def __init__(self, epsilon: int = ..., **kwargs: Any) -> None: ...
    def sample(self, q: Any): ...
    @property
    def epsilon(self): ...
    def set_epsilon(self, epsilon: Any) -> None: ...

class CategoricalEpsilonGreedy(EpsilonGreedy):
    z: Any = ...
    def __init__(self, z: Optional[Any] = ..., **kwargs: Any) -> None: ...
    def sample(self, p: Any, z: Optional[Any] = ...): ...
    def set_z(self, z: Any) -> None: ...
