from rlpyt.envs.atari.atari_env import AtariEnv as AtariEnv
from rlpyt.spaces.int_box import IntBox as IntBox
from rlpyt.utils.quick_args import save__init__args as save__init__args
from typing import Any

class AtariEnv84(AtariEnv):
    ale: Any = ...
    def __init__(self, game: str = ..., frame_skip: int = ..., num_img_obs: int = ..., clip_reward: bool = ..., episodic_lives: bool = ..., max_start_noops: int = ..., repeat_action_probability: float = ..., horizon: int = ..., obs_size: int = ..., fire_on_reset: bool = ...) -> None: ...
    def reset(self): ...
    def fire_and_up(self) -> None: ...
