import gym
from gym.wrappers import TimeLimit
from rlpyt.envs.gym import GymEnvWrapper as GymEnvWrapper
from typing import Any

class TimeLimitMinusOne(TimeLimit):
    def step(self, action: Any): ...

class FrameStack(gym.Wrapper):
    observation_space: Any = ...
    def __init__(self, env: Any, k: Any) -> None: ...
    def reset(self): ...
    def step(self, action: Any): ...

def make(*args: Any, frame_stack: int = ..., from_pixels: bool = ..., height: int = ..., width: int = ..., frame_skip: int = ..., **kwargs: Any): ...
