from rlpyt.utils.launching.affinity import affinity_from_code as affinity_from_code, get_n_run_slots as get_n_run_slots, prepend_run_slot as prepend_run_slot
from rlpyt.utils.launching.variant import save_variant as save_variant
from rlpyt.utils.logging.context import get_log_dir as get_log_dir
from typing import Any, Optional

def log_exps_tree(exp_dir: Any, log_dirs: Any, runs_per_setting: Any) -> None: ...
def log_num_launched(exp_dir: Any, n: Any, total: Any) -> None: ...
def launch_experiment(script: Any, run_slot: Any, affinity_code: Any, log_dir: Any, variant: Any, run_ID: Any, args: Any, python_executable: Optional[Any] = ..., set_egl_device: bool = ...): ...
def run_experiments(script: Any, affinity_code: Any, experiment_title: Any, runs_per_setting: Any, variants: Any, log_dirs: Any, common_args: Optional[Any] = ..., runs_args: Optional[Any] = ..., set_egl_device: bool = ...) -> None: ...
