# Stubs for rlpyt.utils.launching.variant (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from collections import namedtuple
from typing import Any

VARIANT: str

VariantLevel = namedtuple('VariantLevel', ['keys', 'values', 'dir_names'])

def make_variants(*variant_levels: Any): ...
def load_variant(log_dir: Any): ...
def save_variant(variant: Any, log_dir: Any) -> None: ...
def update_config(default: Any, variant: Any): ...
