import torch
from rlpyt.models.mlp import MlpModel as MlpModel
from rlpyt.models.utils import scale_grad as scale_grad
from typing import Any

class DuelingHeadModel(torch.nn.Module):
    advantage_hidden: Any = ...
    advantage_out: Any = ...
    advantage_bias: Any = ...
    value: Any = ...
    def __init__(self, input_size: Any, hidden_sizes: Any, output_size: Any, grad_scale: Any = ...) -> None: ...
    def forward(self, input: Any): ...
    def advantage(self, input: Any): ...

class DistributionalDuelingHeadModel(torch.nn.Module):
    advantage_hidden: Any = ...
    advantage_out: Any = ...
    advantage_bias: Any = ...
    value: Any = ...
    def __init__(self, input_size: Any, hidden_sizes: Any, output_size: Any, n_atoms: Any, grad_scale: Any = ...) -> None: ...
    def forward(self, input: Any): ...
    def advantage(self, input: Any): ...
