# Stubs for rlpyt.replays.sequence.frame (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from rlpyt.replays.async_ import AsyncReplayBufferMixin
from rlpyt.replays.frame import FrameBufferMixin
from rlpyt.replays.sequence.n_step import SequenceNStepReturnBuffer
from rlpyt.replays.sequence.prioritized import PrioritizedSequenceReplay
from rlpyt.replays.sequence.uniform import UniformSequenceReplay
from typing import Any

class SequenceNStepFrameBuffer(FrameBufferMixin, SequenceNStepReturnBuffer):
    def extract_observation(self, T_idxs: Any, B_idxs: Any, T: Any): ...

class UniformSequenceReplayFrameBuffer(UniformSequenceReplay, SequenceNStepFrameBuffer): ...
class PrioritizedSequenceReplayFrameBuffer(PrioritizedSequenceReplay, SequenceNStepFrameBuffer): ...
class AsyncUniformSequenceReplayFrameBuffer(AsyncReplayBufferMixin, UniformSequenceReplayFrameBuffer): ...
class AsyncPrioritizedSequenceReplayFrameBuffer(AsyncReplayBufferMixin, PrioritizedSequenceReplayFrameBuffer): ...
