from rlpyt.replays.async_ import AsyncReplayBufferMixin as AsyncReplayBufferMixin
from rlpyt.replays.sequence.n_step import SequenceNStepReturnBuffer as SequenceNStepReturnBuffer
from typing import Any, Optional

class UniformSequenceReplay:
    batch_T: Any = ...
    def set_batch_T(self, batch_T: Any) -> None: ...
    def sample_batch(self, batch_B: Any, batch_T: Optional[Any] = ...): ...
    def sample_idxs(self, batch_B: Any, batch_T: Any): ...

class UniformSequenceReplayBuffer(UniformSequenceReplay, SequenceNStepReturnBuffer): ...
class AsyncUniformSequenceReplayBuffer(AsyncReplayBufferMixin, UniformSequenceReplayBuffer): ...
