from typing import Any, Optional

color2num: Any

def colorize(string: Any, color: Any, bold: bool = ..., highlight: bool = ...): ...
def mkdir_p(path: Any) -> None: ...
def log(s: Any) -> None: ...

class SimpleMessage:
    msg: Any = ...
    logger: Any = ...
    def __init__(self, msg: Any, logger: Any = ...) -> None: ...
    tstart: Any = ...
    def __enter__(self) -> None: ...
    def __exit__(self, etype: Any, *args: Any) -> None: ...

MESSAGE_DEPTH: int

class Message:
    msg: Any = ...
    def __init__(self, msg: Any) -> None: ...
    tstart: Any = ...
    def __enter__(self) -> None: ...
    def __exit__(self, etype: Any, *args: Any) -> None: ...

def prefix_log(prefix: Any, logger: Any = ...): ...
def tee_log(file_name: Any): ...
def collect_args(): ...
def type_hint(arg_name: Any, arg_type: Any): ...
def tweak(fun_or_val: Any, identifier: Optional[Any] = ...): ...
def tweakval(val: Any, identifier: Any): ...
def tweakfun(fun: Any, alt: Optional[Any] = ...): ...
def query_yes_no(question: Any, default: str = ...): ...
