# Stubs for rlpyt.utils.logging.context (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

LOG_DIR: Any

def get_log_dir(experiment_name: Any, root_log_dir: Optional[Any] = ..., date: bool = ...): ...
def logger_context(log_dir: Any, run_ID: Any, name: Any, log_params: Optional[Any] = ..., snapshot_mode: str = ..., override_prefix: bool = ..., use_summary_writer: bool = ...): ...
def add_exp_param(param_name: Any, param_val: Any, exp_dir: Optional[Any] = ..., overwrite: bool = ...): ...
