from rlpyt.samplers.parallel.base import ParallelSamplerBase as ParallelSamplerBase
from rlpyt.samplers.parallel.cpu.collectors import CpuEvalCollector as CpuEvalCollector, CpuResetCollector as CpuResetCollector
from typing import Any

class CpuSampler(ParallelSamplerBase):
    def __init__(self, *args: Any, CollectorCls: Any = ..., eval_CollectorCls: Any = ..., **kwargs: Any) -> None: ...
    def obtain_samples(self, itr: Any): ...
    def evaluate_agent(self, itr: Any): ...
