# Stubs for rlpyt.samplers.parallel.cpu.sampler (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from rlpyt.samplers.parallel.base import ParallelSamplerBase
from typing import Any

class CpuSampler(ParallelSamplerBase):
    def __init__(self, *args: Any, CollectorCls: Any = ..., eval_CollectorCls: Any = ..., **kwargs: Any) -> None: ...
    def obtain_samples(self, itr: Any): ...
    def evaluate_agent(self, itr: Any): ...
