# Stubs for rlpyt.samplers.async_.action_server (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from rlpyt.samplers.parallel.gpu.action_server import ActionServer, AlternatingActionServer, NoOverlapAlternatingActionServer
from typing import Any

class AsyncActionServer(ActionServer):
    def serve_actions_evaluation(self, itr: Any) -> None: ...

class AsyncAlternatingActionServer(AlternatingActionServer):
    def serve_actions_evaluation(self, itr: Any) -> None: ...

class AsyncNoOverlapAlternatingActionServer(NoOverlapAlternatingActionServer):
    def serve_actions_evaluation(self, itr: Any) -> None: ...
