from rlpyt.samplers.async_.action_server import AsyncAlternatingActionServer as AsyncAlternatingActionServer, AsyncNoOverlapAlternatingActionServer as AsyncNoOverlapAlternatingActionServer
from rlpyt.samplers.async_.gpu_sampler import AsyncGpuSamplerBase as AsyncGpuSamplerBase
from rlpyt.utils.logging import logger as logger
from typing import Any

class AsyncAlternatingSamplerBase(AsyncGpuSamplerBase):
    alternating: bool = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def async_initialize(self, agent: Any, *args: Any, **kwargs: Any): ...
    def launch_workers(self, double_buffer_slice: Any, affinity: Any, seed: Any, n_envs_list: Any) -> None: ...

class AsyncAlternatingSampler(AsyncAlternatingActionServer, AsyncAlternatingSamplerBase): ...
class AsyncNoOverlapAlternatingSampler(AsyncNoOverlapAlternatingActionServer, AsyncAlternatingSamplerBase): ...
