from rlpyt.samplers.buffer import build_samples_buffer as build_samples_buffer
from rlpyt.utils.seed import make_seed as make_seed
from rlpyt.utils.synchronize import drain_queue as drain_queue
from typing import Any, Optional

class AsyncSamplerMixin:
    seed: Any = ...
    double_buffer: Any = ...
    samples_np: Any = ...
    examples: Any = ...
    agent: Any = ...
    def async_initialize(self, agent: Any, bootstrap_value: bool = ..., traj_info_kwargs: Optional[Any] = ..., seed: Optional[Any] = ...): ...

class AsyncParallelSamplerMixin(AsyncSamplerMixin):
    def obtain_samples(self, itr: Any, db_idx: Any): ...
