from rlpyt.samplers.parallel.cpu.collectors import CpuResetCollector as CpuResetCollector, CpuWaitResetCollector as CpuWaitResetCollector
from rlpyt.samplers.parallel.gpu.collectors import GpuResetCollector as GpuResetCollector, GpuWaitResetCollector as GpuWaitResetCollector
from typing import Any

class DoubleBufferCollectorMixin:
    double_buffer: Any = ...
    samples_np: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def collect_batch(self, *args: Any, **kwargs: Any): ...

class DbCpuResetCollector(DoubleBufferCollectorMixin, CpuResetCollector): ...
class DbCpuWaitResetCollector(DoubleBufferCollectorMixin, CpuWaitResetCollector): ...
class DbGpuResetCollector(DoubleBufferCollectorMixin, GpuResetCollector): ...
class DbGpuWaitResetCollector(DoubleBufferCollectorMixin, GpuWaitResetCollector): ...
