# Stubs for rlpyt.samplers.async_.cpu_sampler (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from rlpyt.samplers.async_.base import AsyncParallelSamplerMixin
from rlpyt.samplers.parallel.base import ParallelSamplerBase
from typing import Any

EVAL_TRAJ_CHECK: float

class AsyncCpuSampler(AsyncParallelSamplerMixin, ParallelSamplerBase):
    def __init__(self, *args: Any, CollectorCls: Any = ..., eval_CollectorCls: Any = ..., **kwargs: Any) -> None: ...
    def initialize(self, affinity: Any) -> None: ...
    def obtain_samples(self, itr: Any, db_idx: Any): ...
    def evaluate_agent(self, itr: Any): ...
