from rlpyt.agents.base import AgentInputs as AgentInputs
from rlpyt.samplers.async_.action_server import AsyncActionServer as AsyncActionServer
from rlpyt.samplers.async_.base import AsyncParallelSamplerMixin as AsyncParallelSamplerMixin
from rlpyt.samplers.async_.collectors import DbGpuResetCollector as DbGpuResetCollector
from rlpyt.samplers.parallel.base import ParallelSamplerBase as ParallelSamplerBase
from rlpyt.samplers.parallel.gpu.collectors import GpuEvalCollector as GpuEvalCollector
from rlpyt.samplers.parallel.gpu.sampler import GpuSamplerBase as GpuSamplerBase, build_step_buffer as build_step_buffer
from rlpyt.samplers.parallel.worker import sampling_process as sampling_process
from rlpyt.utils.collections import AttrDict as AttrDict
from rlpyt.utils.logging import logger as logger
from rlpyt.utils.seed import make_seed as make_seed
from typing import Any

class AsyncGpuSamplerBase(AsyncParallelSamplerMixin, ParallelSamplerBase):
    def __init__(self, *args: Any, CollectorCls: Any = ..., eval_CollectorCls: Any = ..., **kwargs: Any) -> None: ...
    world_size: Any = ...
    n_worker: Any = ...
    eval_n_envs_per: Any = ...
    eval_n_envs: Any = ...
    eval_max_T: Any = ...
    servers: Any = ...
    def initialize(self, affinity: Any) -> None: ...
    def shutdown(self) -> None: ...
    rank: Any = ...
    samples_np: Any = ...
    bootstrap_value_pair: Any = ...
    def action_server_process(self, rank: Any, env_ranks: Any, double_buffer_slice: Any, affinity: Any, seed: Any, n_envs_list: Any) -> None: ...
    sync: Any = ...
    agent_inputs: Any = ...
    eval_step_buffer_pyt: Any = ...
    eval_step_buffer_np: Any = ...
    eval_agent_inputs: Any = ...
    double_buffer: Any = ...
    workers: Any = ...
    def launch_workers(self, double_buffer_slice: Any, affinity: Any, seed: Any, n_envs_list: Any) -> None: ...
    def shutdown_workers(self) -> None: ...

class AsyncGpuSampler(AsyncActionServer, AsyncGpuSamplerBase): ...
