from rlpyt.samplers.async_.base import AsyncSamplerMixin as AsyncSamplerMixin
from rlpyt.samplers.async_.collectors import DbCpuResetCollector as DbCpuResetCollector
from rlpyt.samplers.base import BaseSampler as BaseSampler
from rlpyt.samplers.serial.collectors import SerialEvalCollector as SerialEvalCollector
from rlpyt.utils.collections import AttrDict as AttrDict
from rlpyt.utils.logging import logger as logger
from typing import Any

class AsyncSerialSampler(AsyncSamplerMixin, BaseSampler):
    def __init__(self, *args: Any, CollectorCls: Any = ..., eval_CollectorCls: Any = ..., **kwargs: Any) -> None: ...
    eval_collector: Any = ...
    collector: Any = ...
    agent_inputs: Any = ...
    traj_infos: Any = ...
    sync: Any = ...
    def initialize(self, affinity: Any) -> None: ...
    def obtain_samples(self, itr: Any, db_idx: Any): ...
    def evaluate_agent(self, itr: Any): ...
