from typing import Any, Optional

def select_at_indexes(indexes: Any, array: Any): ...
def to_onehot(indexes: Any, dim: Any, dtype: Optional[Any] = ...): ...
def from_onehot(onehot: Any, dtype: Optional[Any] = ...): ...
def valid_mean(array: Any, valid: Optional[Any] = ..., axis: Optional[Any] = ...): ...
def infer_leading_dims(array: Any, dim: Any): ...
