from typing import Any

def iterate_mb_idxs(data_length: Any, minibatch_size: Any, shuffle: bool = ...) -> None: ...
def zeros(shape: Any, dtype: Any): ...
def empty(shape: Any, dtype: Any): ...
def extract_sequences(array_or_tensor: Any, T_idxs: Any, B_idxs: Any, T: Any): ...
