from rlpyt.utils.logging import logger as logger
from typing import Any

class ProgBarCounter:
    total_count: Any = ...
    max_progress: int = ...
    cur_progress: int = ...
    cur_count: int = ...
    pbar: Any = ...
    def __init__(self, total_count: Any) -> None: ...
    def update(self, current_count: Any) -> None: ...
    def stop(self) -> None: ...
