# Stubs for rlpyt.utils.quick_args (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def save__init__args(values: Any, underscore: bool = ..., overwrite: bool = ..., subclass_only: bool = ...) -> None: ...
