from rlpyt.utils.logging.console import colorize as colorize
from typing import Any

seed_: Any

def set_seed(seed: Any) -> None: ...
def get_seed(): ...
def make_seed(): ...
def set_envs_seeds(envs: Any, seed: Any) -> None: ...
