from typing import Any

valid_chars: Any
typecode_to_type: Any

def address_of_buffer(buf: Any): ...

class ShmemBufferWrapper:
    size: Any = ...
    def __init__(self, tag: Any, size: Any, create: bool = ...) -> None: ...
    def get_address(self): ...
    def __del__(self) -> None: ...

def ShmemRawArray(typecode_or_type: Any, size_or_initializer: Any, tag: Any, create: bool = ...): ...
def NpShmemArray(shape: Any, dtype: Any, tag: Any, create: bool = ...): ...
def get_random_tag(): ...
