from typing import Any

class RWLock:
    write_lock: Any = ...
    def __init__(self) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, *args: Any) -> None: ...
    def acquire_write(self) -> None: ...
    def release_write(self) -> None: ...
    def acquire_read(self) -> None: ...
    def release_read(self) -> None: ...

def drain_queue(queue_obj: Any, n_sentinel: int = ..., guard_sentinel: bool = ...): ...
def find_port(offset: Any): ...
