import torch
from rlpyt.utils.tensor import infer_leading_dims as infer_leading_dims, restore_leading_dims as restore_leading_dims
from typing import Any

class UlEncoderModel(torch.nn.Module):
    conv: Any = ...
    head: Any = ...
    def __init__(self, conv: Any, latent_size: Any, conv_out_size: Any) -> None: ...
    def forward(self, observation: Any): ...
