import torch
from typing import Any, Optional

class MlpModel(torch.nn.Module):
    model: Any = ...
    def __init__(self, input_size: Any, hidden_sizes: Any, output_size: Optional[Any] = ..., nonlinearity: Any = ...) -> None: ...
    def forward(self, input: Any): ...
    @property
    def output_size(self): ...
