# Stubs for rlpyt.models.running_mean_std (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import torch.distributed
from typing import Any

class RunningMeanStdModel(torch.nn.Module):
    shape: Any = ...
    def __init__(self, shape: Any) -> None: ...
    def update(self, x: Any) -> None: ...
