from typing import Any, Optional

class BaseReplayBuffer:
    async_: bool = ...
    def append_samples(self, samples: Any) -> None: ...
    def sample_batch(self, batch_B: Any, batch_T: Optional[Any] = ...) -> None: ...
