from rlpyt.utils.buffer import buffer_from_example as buffer_from_example, get_leading_dims as get_leading_dims
from rlpyt.utils.collections import namedarraytuple as namedarraytuple
from rlpyt.utils.logging import logger as logger
from typing import Any

BufferSamples: Any

class FrameBufferMixin:
    n_frames: Any = ...
    samples_frames: Any = ...
    samples_new_frames: Any = ...
    off_forward: Any = ...
    def __init__(self, example: Any, **kwargs: Any) -> None: ...
    def append_samples(self, samples: Any): ...
