from rlpyt.samplers.parallel.gpu.action_server import AlternatingActionServer as AlternatingActionServer, NoOverlapAlternatingActionServer as NoOverlapAlternatingActionServer
from rlpyt.samplers.parallel.gpu.sampler import GpuSamplerBase as GpuSamplerBase
from typing import Any

class AlternatingSamplerBase(GpuSamplerBase):
    alternating: bool = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def initialize(self, agent: Any, *args: Any, **kwargs: Any): ...

class AlternatingSampler(AlternatingActionServer, AlternatingSamplerBase): ...
class NoOverlapAlternatingSampler(NoOverlapAlternatingActionServer, AlternatingSamplerBase): ...
