# Stubs for rlpyt.spaces.base (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

class Space:
    def sample(self) -> None: ...
    def null_value(self) -> None: ...
