from rlpyt.spaces.base import Space as Space
from typing import Any

class Composite(Space):
    def __init__(self, spaces: Any, NamedTupleCls: Any) -> None: ...
    def sample(self): ...
    def null_value(self): ...
    @property
    def shape(self): ...
    @property
    def names(self): ...
    @property
    def spaces(self): ...
