from rlpyt.algos.qpg.ddpg import DDPG as DDPG
from rlpyt.utils.quick_args import save__init__args as save__init__args
from rlpyt.utils.tensor import valid_mean as valid_mean
from typing import Any

class TD3(DDPG):
    def __init__(self, batch_size: int = ..., replay_ratio: int = ..., target_update_tau: float = ..., target_update_interval: int = ..., policy_update_interval: int = ..., mu_learning_rate: float = ..., q_learning_rate: float = ..., **kwargs: Any) -> None: ...
    def initialize(self, *args: Any, **kwargs: Any) -> None: ...
    def async_initialize(self, *args: Any, **kwargs: Any): ...
    def q_loss(self, samples: Any, valid: Any): ...
